#! /usr/bin/sh 

# Gitpod CDE init script

# Aliases
#alias cl="clear && ls" # Clear and list

# Functions
#bak() {
#    cp "$1" "$1.bak"
#}

# APT updates
sudo apt update
#sudo apt upgrade -y --fix-missing

sudo apt install qt6-base-dev libqt6core5compat6 -y

# Cleanup
sudo apt autoremove
