# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Austin CI with Gradle

on:  
  pull_request:
    branches: [ 1.18-DEV ]
    
  push:
    branches: [ 1.18-DEV ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: build
        
    - name: Export to JAR
      uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
      with:
        arguments: jar
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: xenon-build
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/*.jar
        
    - name: Release & Assets
      # You may pin to the exact commit or the version.
      # uses: Hs1r1us/Release-AIO@354b8db50d5b6310b621cb6c5e29d1f8e611aff7
      uses: Hs1r1us/Release-AIO@v1.0
      with:
        # The name of the tag
        tag_name: test
      env:
        GITHUB_TOKEN: ${{ github.token }}
