# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle CI

on:  
  pull_request:
    branches: [ 1.20-DEV ]
    
  push:
    branches: [ 1.20-DEV ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v4.1.0
      name: Checkout
      
    - name: Set up JDK 18
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@2.8.0
      with:
        arguments: build
        
    - name: Export to JAR
      uses: gradle/gradle-build-action@2.8.0
      with:
        arguments: jar
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # A file, directory or wildcard pattern that describes what to upload
        path: ./build/libs/*.jar
